project_id = "ijzivmrodhxtjnjxsgvo"

[functions.manage-users]
verify_jwt = false

[functions.prayer-times]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.send-bulk-email]
verify_jwt = false

[functions.check-absence-warnings]
verify_jwt = false

[functions.award-monthly-badges]
verify_jwt = false