ALTER TABLE public.students
  ADD COLUMN IF NOT EXISTS national_id TEXT,
  ADD COLUMN IF NOT EXISTS nationality TEXT DEFAULT 'سعودي',
  ADD COLUMN IF NOT EXISTS school_name TEXT,
  ADD COLUMN IF NOT EXISTS grade TEXT,
  ADD COLUMN IF NOT EXISTS memorization_amount TEXT,
  ADD COLUMN IF NOT EXISTS student_phone TEXT,
  ADD COLUMN IF NOT EXISTS guardian_phone_alt TEXT,
  ADD COLUMN IF NOT EXISTS guardian_national_id TEXT,
  ADD COLUMN IF NOT EXISTS guardian_relation TEXT DEFAULT 'الأب',
  ADD COLUMN IF NOT EXISTS guardian_work TEXT,
  ADD COLUMN IF NOT EXISTS residence_location TEXT,
  ADD COLUMN IF NOT EXISTS accompanied_by TEXT,
  ADD COLUMN IF NOT EXISTS previously_enrolled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS father_alive BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS mother_alive BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS lives_with TEXT DEFAULT 'الوالدين',
  ADD COLUMN IF NOT EXISTS lives_with_other TEXT,
  ADD COLUMN IF NOT EXISTS has_diabetes BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_epilepsy BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_hypertension BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_hearing_impairment BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_vision_impairment BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_chest_sensitivity BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_asthma BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_anemia BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_frequent_urination BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS other_health_conditions TEXT,
  ADD COLUMN IF NOT EXISTS registration_date_hijri TEXT;
